### ISSUE TITLE
No Data Due to SSL Error

### ISSUE THREAD

**Issue by MichaelBone** [planningalerts-scrapers/darebin#5]
Since the recent update of the MITM proxy this scraper has been failing with another SSL error.

```
scraper.rb:32: warning: already initialized constant OpenSSL::SSL::SSLContext::DEFAULT_PARAMS
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/openssl/ssl.rb:23: warning: previous definition of DEFAULT_PARAMS was here
/app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: sslv3 alert handshake failure (OpenSSL::SSL::SSLError)
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:857:in `start'
	from /app/vendor/bundle/ruby/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
	from /app/vendor/bundle/ruby/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
	from /app/vendor/bundle/ruby/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
	from /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:274:in `fetch'
	from /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
	from scraper.rb:35:in `<main>'
```

**Comment by MichaelBone** [comment]
This is fixed by f62a57d.
